######################################
# NOTE: Before running this pipeline to generate a new nuget package, update the version string in two places
#      1) update the name: string below (line 6)     -- this is the version for the nuget package (e.g. 1.0.0)
#      2) update \libs\host\GarnetServer.cs readonly string version  (~line 45)   -- NOTE - these two values need to be the same 
###################################### 
name: 1.0.4
trigger: none
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Phase_1
  displayName: Assessment
  cancelTimeoutInMinutes: 1
  pool:
    name: Azure Pipelines
  steps:
  - checkout: self
    clean: False
    submodules: recursive
    persistCredentials: True
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 6.0.x
    inputs:
      version: 6.0.x
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 7.0.x
    inputs:
      version: 7.0.x
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 8.0.x
    inputs:
      version: 8.0.x
  - task: NuGetToolInstaller@1
    displayName: Nuget Tool Installer
    inputs:
      versionspec: '*'
      checkLatest: true
  - task: NuGetAuthenticate@1
    displayName: NuGet Authenticate
  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: '**/Garnet.*.csproj'
      arguments: -c Release
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
    displayName: Sign the binaries
    enabled: True
    inputs:
      ConnectedServiceName: Garnet Code Signing
      FolderPath: .
      Pattern: Garnet.server.dll,Garnet.client.dll,Garnet.common.dll,Garnet.cluster.dll,Garnet.host.dll,HdrHistogram.dll,Tsavorite.core.dll,Tsavorite.devices.AzureStorageDevice.dll,native_device.dll
      signConfigType: inlineSignParams
      inlineOperation: >-
        [
            {
                "keyCode": "CP-230012",
                "operationSetCode": "SigntoolSign",
                "parameters": [
                {
                    "parameterName": "OpusName",
                    "parameterValue": "Microsoft"
                },
                {
                    "parameterName": "OpusInfo",
                    "parameterValue": "http://www.microsoft.com"
                },
                {
                    "parameterName": "FileDigest",
                    "parameterValue": "/fd \"SHA256\""
                },
                {
                    "parameterName": "PageHash",
                    "parameterValue": "/NPH"
                },
                {
                    "parameterName": "TimeStamp",
                    "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                }
                ],
                "toolName": "sign",
                "toolVersion": "1.0"
            },
            {
                "keyCode": "CP-230012",
                "operationSetCode": "SigntoolVerify",
                "parameters": [ ],
                "toolName": "sign",
                "toolVersion": "1.0"
            }
        ]
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: dir
  - task: CopyFiles@2
    displayName: 'Copy Files to Artifacts dir: $(build.artifactstagingdirectory)'
    inputs:
      Contents: '**/bin/AnyCPU/$(BuildConfiguration)/**/*'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: NuGetCommand@2
    displayName: nuget pack Garnet
    enabled: True
    inputs:
      command: custom
      arguments: pack Garnet.nuspec -OutputDirectory $(Build.ArtifactStagingDirectory) -Properties Configuration=$(BuildConfiguration) -Symbols -SymbolPackageFormat snupkg -version $(Build.BuildNumber) -Verbosity Detailed
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
    displayName: Sign the NuGet Package
    enabled: True
    inputs:
      ConnectedServiceName: Garnet Code Signing
      FolderPath: $(Build.ArtifactStagingDirectory)
      Pattern: Microsoft.Garnet.*.nupkg
      signConfigType: inlineSignParams
      inlineOperation: >-
        [
            {
                "keyCode": "CP-401405",
                "operationSetCode": "NuGetSign",
                "parameters": [ ],
                "toolName": "sign",
                "toolVersion": "1.0"
            },
            {
                "keyCode": "CP-401405",
                "operationSetCode": "NuGetVerify",
                "parameters": [ ],
                "toolName": "sign",
                "toolVersion": "1.0"
            }
        ]
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    enabled: True
  - task: GitHubRelease@0
    displayName: 'Create the GitHub release'
    enabled: true
    inputs:
      gitHubConnection: ADO_to_Github_ServiceConnection
      tagSource: manual
      tag: 'v$(Build.BuildNumber)'
      title: 'Garnet v$(Build.BuildNumber)'
      releaseNotesSource: input
      releaseNotes: |
       Get NuGet binaries at:
       * https://www.nuget.org/packages/Microsoft.Garnet

       More information at:
       * https://microsoft.github.io/garnet
       * https://github.com/microsoft/garnet
       * https://www.microsoft.com/en-us/research/project/garnet
     
      assets: '$(Build.ArtifactStagingDirectory)/*.nupkg'
  - task: NuGetCommand@2
    displayName: 'Push to NuGet.org'
    enabled: true
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: GarnetADO_to_Nuget